### ISSUE TITLE
Error building TAO/orbsvcs

### ISSUE THREAD

**Issue by alexchandel** [DOCGroup/ACE_TAO#2047] opened 2023-02-03 21:04 UTC
### Version

ACE+TAO 7.0.11 [full release](https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-7_0_11/ACE+TAO-7.0.11.zip)

### Host machine and operating system / Target machine and operating system (if different from host)

macOS 12.6.3

### Compiler name and version (including patch level)

Apple clang version 14.0.0 (clang-1400.0.29.202)

### The $ACE_ROOT/ace/config.h file

<summary>Basically a link to `config-macosx-mojave.h`
<details>
<pre>
#ifndef ACE_CONFIG_MACOSX_CUSTOM_H
#define ACE_CONFIG_MACOSX_CUSTOM_H

#ifndef __GNUC__
#define __GNUC__ 4
#endif
#ifndef __GNUC_MINOR__
#define __GNUC_MINOR__ 2
#endif

#define ACE_HAS_STANDARD_CPP_LIBRARY 1

#include "ace/config-macosx-mojave.h"

#endif // ACE_CONFIG_MACOSX_CUSTOM_H
</pre>
</details>
</summary>

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

<summary>Basically a link to `platform_macosx_monterey.GNU`
<details>
<pre>
debug		= 0
inline		= 1
optimize	= 1
static_libs	= 1
shared_libs	= 1
ssl			= 0
buildbits	= 64

OCFLAGS		+= -Oz -Wno-deprecated-declarations
OCCFLAGS	+= -Oz -Wno-deprecated-declarations
CFLAGS		+= -Wno-deprecated-declarations
CCFLAGS		+= -Wno-deprecated-declarations
LDFLAGS		+=

include $(ACE_ROOT)/include/makeinclude/platform_macosx_monterey.GNU
</pre>
</details>
</summary>

### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features

Unmodified.

### AREA/CLASS/EXAMPLE AFFECTED:

Making `FaultTolerance` in `TAO/orbsvcs/orbsvcs`

### The problem effects:

Compilation of TAO orbsvcs.

### Synopsis / Description / Repeat by

My build invocation is roughly:

```sh
export ACE_ROOT=/Users/alex/Downloads/ACE_wrappers
export TAO_ROOT=$ACE_ROOT/TAO
cd "$ACE_ROOT/ace" && make
cd "$ACE_ROOT/apps/gperf/src" && make
cd "$TAO_ROOT/TAO_IDL" && make
cd "$TAO_ROOT/tao" && make
cd "$TAO_ROOT/orbsvcs" && make
cd "$TAO_ROOT/orbsvcs/orbsvcs" && make TAO_ORBSVCS=CosEvent_Serv,CosProperty,CosConcurrency,CosTime,RTEvent,RTEventLogAdmin_Serv,DsLogAdmin_Serv,Kokyu,RTSched,FaultTolerance,CosLoadBalancing,CosLifeCycle_Serv,CosTrading,CosNotification,CosNotification_Serv,CosNotification_MC_Ext,PortableGroup
```

The second last call attempts to build `FaultTolerance`, which fails:

```sh
touch .depend.FaultTolerance_Idl5
touch .depend.FaultTolerance_Idl4
touch .depend.FaultTolerance_Idl3
touch .depend.FaultTolerance_Idl2
touch .depend.FaultTolerance_Idl1
touch .depend.FaultTolerance

GNUmakefile: /Users/alex/Downloads/ACE_wrappers/TAO/orbsvcs/orbsvcs/GNUmakefile.FaultTolerance MAKEFLAGS=

../../../bin/tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I ../.. -I../../orbsvcs -Wb,versioning_begin=TAO_BEGIN_VERSIONED_NAMESPACE_DECL -Wb,versioning_end=TAO_END_VERSIONED_NAMESPACE_DECL -Wb,export_macro=TAO_FT_Export -Wb,export_include=orbsvcs/FaultTolerance/fault_tol_export.h -Wb,skel_export_include=tao/PortableServer/PolicyS.h FT_CORBA.idl
clang++ -Wno-deprecated-declarations -Wnon-virtual-dtor -std=c++11 -Oz -Wno-deprecated-declarations -m64 -Wall -Wextra -Wpointer-arith -DACE_HAS_CUSTOM_EXPORT_MACROS=0  -DNDEBUG  -I/Users/alex/Downloads/ACE_wrappers -DACE_NDEBUG -D__ACE_INLINE__ -I../../.. -I../.. -I../../orbsvcs -DTAO_HAS_TYPED_EVENT_CHANNEL -DTAO_FT_BUILD_DLL -DACE_AS_STATIC_LIBS -DTAO_AS_STATIC_LIBS  -c -o .obj/FT_CORBAC.o /Users/alex/Downloads/ACE_wrappers/TAO/orbsvcs/orbsvcs/FT_CORBAC.cpp
clang++ -Wno-deprecated-declarations -Wnon-virtual-dtor -std=c++11 -Oz -Wno-deprecated-declarations -m64 -Wall -Wextra -Wpointer-arith -DACE_HAS_CUSTOM_EXPORT_MACROS=0  -DNDEBUG  -I/Users/alex/Downloads/ACE_wrappers -DACE_NDEBUG -D__ACE_INLINE__ -I../../.. -I../.. -I../../orbsvcs -DTAO_HAS_TYPED_EVENT_CHANNEL -DTAO_FT_BUILD_DLL -DACE_AS_STATIC_LIBS -DTAO_AS_STATIC_LIBS  -c -o .obj/FT_CORBAS.o /Users/alex/Downloads/ACE_wrappers/TAO/orbsvcs/orbsvcs/FT_CORBAS.cpp
../../../bin/tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I ../.. -I../../orbsvcs -Wb,versioning_begin=TAO_BEGIN_VERSIONED_NAMESPACE_DECL -Wb,versioning_end=TAO_END_VERSIONED_NAMESPACE_DECL -Wb,export_macro=TAO_FT_Export -Wb,export_include=orbsvcs/FaultTolerance/fault_tol_export.h -Wb,skel_export_include=tao/PortableServer/PolicyS.h FT_FaultDetectorFactory.idl
clang++ -Wno-deprecated-declarations -Wnon-virtual-dtor -std=c++11 -Oz -Wno-deprecated-declarations -m64 -Wall -Wextra -Wpointer-arith -DACE_HAS_CUSTOM_EXPORT_MACROS=0  -DNDEBUG  -I/Users/alex/Downloads/ACE_wrappers -DACE_NDEBUG -D__ACE_INLINE__ -I../../.. -I../.. -I../../orbsvcs -DTAO_HAS_TYPED_EVENT_CHANNEL -DTAO_FT_BUILD_DLL -DACE_AS_STATIC_LIBS -DTAO_AS_STATIC_LIBS  -c -o .obj/FT_FaultDetectorFactoryC.o /Users/alex/Downloads/ACE_wrappers/TAO/orbsvcs/orbsvcs/FT_FaultDetectorFactoryC.cpp
In file included from /Users/alex/Downloads/ACE_wrappers/TAO/orbsvcs/orbsvcs/FT_FaultDetectorFactoryC.cpp:29:
/Users/alex/Downloads/ACE_wrappers/TAO/orbsvcs/orbsvcs/FT_FaultDetectorFactoryC.h:66:10: fatal error: 'orbsvcs/FT_ReplicaC.h' file not found
#include "orbsvcs/FT_ReplicaC.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [.obj/FT_FaultDetectorFactoryC.o] Error 1
make[1]: *** [FaultTolerance] Error 2
make: *** [tao] Error 2
```

There is no `FT_ReplicaC.h` or `FT_ReplicaC.cpp` to be found in the build directory.

**Comment by alexchandel** [comment] 2023-02-03 22:11
Attempting alternate build orders like these also fails:
```sh
export ACE_ROOT=/Users/alex/Downloads/ACE_wrappers
export TAO_ROOT=$ACE_ROOT/TAO
cd "$ACE_ROOT/ace" && make
cd "$ACE_ROOT/apps/gperf/src" && make
cd "$TAO_ROOT/TAO_IDL" && make
cd "$TAO_ROOT/tao" && make
cd "$TAO_ROOT/orbsvcs/orbsvcs" && make
cd "$TAO_ROOT/orbsvcs" && make
```

```sh
export ACE_ROOT=/Users/alex/Downloads/ACE_wrappers
export TAO_ROOT=$ACE_ROOT/TAO
cd "$ACE_ROOT/ace" && make
cd "$ACE_ROOT/apps/gperf/src" && make
cd "$TAO_ROOT/TAO_IDL" && make
cd "$TAO_ROOT/tao" && make
cd "$TAO_ROOT/orbsvcs" && make
cd "$TAO_ROOT/orbsvcs/orbsvcs" && make
```

**Comment by alexchandel** [comment] 2023-02-03 22:15
Ideally not, I wasn't sure how to disable them without disabling other dependencies.

**Comment by mitza-oci** [comment] 2023-02-03 22:16
It depends if you're OK with generating makefiles or if you need to use the ones that are part of the release archive.

**Comment by alexchandel** [comment] 2023-02-03 22:17
I used to generate makefiles with `cd "$$TAO_ROOT" && perl "$$ACE_ROOT/bin/mwc.pl" -type gnuace TAO_ACE.mwc` but I switched to release ones in case that was causing the error.

**Comment by mitza-oci** [comment] 2023-02-03 23:00
If you want to keep the makefiles that are packaged, try building ACE in one step and TAO in the next.  Use makefile targets in each step to specify what you need, and the dependencies should be determined automatically (the only part it doesn't do is the dependencies from code in $TAO_ROOT to code in $ACE_ROOT).
```
make -C $ACE_ROOT gperf
make -C $TAO_ROOT Naming_Service [other targets]
```

This probably won't solve the issue with FT_Replica.idl.

**Comment by alexchandel** [comment] 2023-02-04 03:26
Well that's unsettling, because this built all the libraries I needed with no error:

```sh
export ACE_ROOT=/Users/alex/Downloads/ACE_wrappers
export TAO_ROOT=$ACE_ROOT/TAO
cp config.h $ACE_ROOT/ace/
cp platform_macros.GNU $ACE_ROOT/include/makeinclude/
make -C $ACE_ROOT gperf ACE_ETCL ACE_ETCL_Parser
make -C $TAO_ROOT CosConcurrency CosEvent_Service Naming_Service Notify_Service nslist
```

`FT_ReplicaC.h` still isn't created, but I don't think I needed it. It's probably worth figuring out why those individual make calls didn't handle the `FT_Replica.idl` dependency.

**Comment by jwillemsen** [comment] 2023-02-06 08:12
When you want to build a specific subset I normally use the source only distribution and create a custom mwc file which only the parts needed for a specific effort.

**Comment by mitza-oci** [comment] 2023-02-06 15:40
> When you want to build a specific subset I normally use the source only distribution and create a custom mwc file which only the parts needed for a specific effort.

This is one approach, but to use it you need to know (or look up) the inter-project dependencies.  It may be easier for maintainers who already know these things.

The makefiles generated by the release script, or similarly "wide ranging" workspaces like TAO_ACE.mwc have all of those inter-project dependencies already encoded.  The advantage here is that the user can just specify the artifacts that are directly needed (nslist and Naming_Service) and have GNU Make determine needed dependencies from there.

**Comment by mitza-oci** [comment] 2023-02-08 22:59
Since I was not able to reproduce the `FT_Replica.idl` problem, I suggest we close this one.  If it is still an issue, getting the reproducer into GitHub Actions would be helpful.

**Closed** 2023-02-09 18:44 UTC
