### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cloudjacky** [DOCGroup/ACE_TAO#1411] opened 2021-01-14 06:09 UTC
### Version
6.5.12

### Host machine and operating system
ubuntu 16.04
### The $ACE_ROOT/ace/config.h file

config-linux.h

### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file

platform_linux.GNU

### AREA/CLASS/EXAMPLE AFFECTED:

make failed

### Synopsis

run 'make' at $ACE_ROOT
ERROR: make: *** No targets specified and no makefile found.  Stop.

### Description
at $ACE_ROOT/ace， created 'config.h', and $ACE_ROOT/include/makefile/, created 'platform_macros.GNU', when run 'make' at $ACE_ROOT, error report 'No targets specified and no makefile found'!

**Comment by jwillemsen** [comment] 2021-01-14 07:34
Duplicate of #1410

**Closed by jwillemsen** 2021-01-14 07:34 UTC
